from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet


def generate_report(output_path, prediction_data):
    """
    Generate a professional PDF report for a brain tumor prediction.

    Args:
        output_path (str): Path to save the PDF report.
        prediction_data (dict): Dictionary containing:
            - 'label': Predicted tumor type
            - 'confidence': Prediction confidence (%)
            - 'severity': Severity analysis dict
            - 'image_path': Path to the uploaded image
            - 'quality': Image quality details
    """
    doc = SimpleDocTemplate(output_path)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = styles['Title']
    story.append(Paragraph("Brain Tumor Detection Report", title_style))
    story.append(Spacer(1, 20))

    # Horizontal line
    story.append(Paragraph("<hr/>", styles['Normal']))
    story.append(Spacer(1, 12))

    # Patient/Scan Info Section
    heading_style = styles['Heading2']
    normal_style = styles['Normal']

    story.append(Paragraph("Scan Analysis Results", heading_style))
    story.append(Spacer(1, 8))

    label = prediction_data.get('label', 'Unknown')
    confidence = prediction_data.get('confidence', 0)
    story.append(Paragraph(f"<b>Predicted Condition:</b> {label}", normal_style))
    story.append(Spacer(1, 4))
    story.append(Paragraph(f"<b>Confidence Level:</b> {confidence:.1f}%", normal_style))
    story.append(Spacer(1, 16))

    # Severity Section
    severity = prediction_data.get('severity', {})
    if severity:
        story.append(Paragraph("Severity Assessment", heading_style))
        story.append(Spacer(1, 8))
        story.append(Paragraph(f"<b>Severity Level:</b> {severity.get('severity', 'N/A')}", normal_style))
        story.append(Spacer(1, 4))
        story.append(Paragraph(f"<b>Risk Level:</b> {severity.get('risk_level', 'N/A')}", normal_style))
        story.append(Spacer(1, 4))
        story.append(Paragraph(f"<b>Description:</b> {severity.get('description', 'N/A')}", normal_style))
        story.append(Spacer(1, 12))

        # Recommendations
        recommendations = severity.get('recommendations', [])
        if recommendations:
            story.append(Paragraph("Recommendations", heading_style))
            story.append(Spacer(1, 8))
            for i, rec in enumerate(recommendations, 1):
                story.append(Paragraph(f"{i}. {rec}", normal_style))
                story.append(Spacer(1, 4))
            story.append(Spacer(1, 12))

    # Image Quality Section
    quality = prediction_data.get('quality', {})
    if quality:
        story.append(Paragraph("Image Quality Assessment", heading_style))
        story.append(Spacer(1, 8))
        details = quality.get('details', {})
        for key, value in details.items():
            story.append(Paragraph(f"<b>{key.replace('_', ' ').title()}:</b> {value}", normal_style))
            story.append(Spacer(1, 4))
        story.append(Spacer(1, 12))

    # Disclaimer
    story.append(Paragraph("<hr/>", styles['Normal']))
    story.append(Spacer(1, 8))
    disclaimer_text = (
        "<i><b>Disclaimer:</b> This report is generated by an AI-based system and is intended "
        "for informational purposes only. It should NOT be used as a substitute for professional "
        "medical diagnosis. Please consult a qualified healthcare provider for proper evaluation "
        "and treatment decisions.</i>"
    )
    story.append(Paragraph(disclaimer_text, normal_style))

    # Build PDF
    doc.build(story)
    return output_path
